### Perceptron

Practica 7

Sinencio Granados Dante Jusepee, 316246019

In [65]:
import numpy as np
import random as rnd

class Perceptron:

    def __init__(self, alpha, theta, w):
        """
        Constructor de nuestros atributos para el perceptron
        """
        self.alpha = alpha
        self.theta = theta
        self.w = w

    def escalon(self, arr):
        """
        Metodo para checar si el valor resultante en los arreglos es mayor 
        a 0, si lo es regresa 1
        """
        for i in range(len(arr)):
            if arr[i] >=0: arr[i] = 1
            else: arr[i] = 0
        return arr

    def prediccion(self, arr):
        """
        Metodo para aplicar el escalon a las matrices
        """
        return self.escalon(np.dot(arr, self.w) - self.theta)

    def error(self, entrada, salida):
        """
        Metodo para restar las entradas de las salidas
        """
        return entrada - salida


In [66]:
def add_method(cls):
    """
    Funcion para poder conectar las funciones entre diferentes recuadros 
    del notebook
    """
    def conector(fun):
        setattr(cls, fun.__name__, fun)
        return fun
    return conector

## Reporte

No supe como hacer el reporte para que se viera bonito asi que lo hare en esta notebook junto a la practica.

Lo que se puede ver del entrenamiento es que en cada entrada que pasamos vemos lo que nos regresa el escalon y le aplicamos el error para ir modificando el perceptron cada iteracion.

In [86]:
@add_method(Perceptron)
def entrena(self, percep, iteraciones):
    """
    Funcion entrenadora, recibe un perceptron y un numero de iteraciones
    y regresa el perceptron entrenado
    """
    (a,dim) = percep.shape
    entrada = percep[:,dim-1]
    x = percep[:,:dim-1].T
    for i in range(iteraciones):
        salida = self.escalon(np.dot(x.T, self.w) - self.theta)
        error = self.error(entrada, salida)
        self.w = self.w + np.dot(self.alpha*x, error)
    return salida


"""
Declaramos los peceptrones de AND y OR
"""
theta = rnd.uniform(-0.5, 0.5)
w = np.random.uniform(-0.5, 0.5, size=4)
perceptronAND = Perceptron(0.04, theta, w)
perceptronOR = Perceptron(0.04, theta, w)


#Primer arreglo de entrenamiento, meteremos los valores "predeterminados" 
# 0 y 1.
inicial = np.array([[1,0,0,0,0],[1,1,1,1,1]])

#Segundo arreglo de entrenamiento, metreremos todos los valores posibles.
And2 = np.array([[1,0,0,0,0],[1,0,0,1,0],[1,0,1,0,0],
                [1,0,1,1,0],[1,1,0,0,0],[1,1,0,1,0],
                [1,1,1,0,0],[1,1,1,1,1]])

Or2 = np.array([[1,0,0,0,0],[1,0,0,1,1],[1,0,1,0,1],
                [1,0,1,1,1],[1,1,0,0,1],[1,1,0,1,1],
                [1,1,1,0,1],[1,1,1,1,1]])

#Tercer arreglo de entrenamiento, meteremos pares de numeros
And3 = np.array([[1,1,0,0,0],[1,0,1,0,0],[1,0,0,1,0],
                [1,1,1,0,0],[1,1,0,1,0],[1,0,1,1,0]])

Or3 = np.array([[1,1,0,0,1],[1,0,1,0,1],[1,0,0,1,1],
                [1,1,1,0,1],[1,1,0,1,1],[1,0,1,1,1]])

#Cuarto arreglo de entrenamiento, sumaremos binariamente desde la izquierda
And4 = np.array([[1,0,0,0,0],[1,1,0,0,0],[1,0,1,0,0],
                [1,1,1,0,0],[1,0,0,1,0],[1,1,0,1,0],
                [1,1,0,1,0],[1,1,1,1,1]])

Or4 = np.array([[1,0,0,0,0],[1,1,0,0,1],[1,0,1,0,1],
                [1,1,1,0,1],[1,0,0,1,1],[1,1,0,1,1],
                [1,1,0,1,1],[1,1,1,1,1]])

#Quinto arreglo de entrenamiento, meteremos conjuntos aleatorios
And5 = np.array([[1,1,1,1,1],[1,0,0,1,0],[1,1,0,1,0],
                [1,1,1,0,0],[1,1,0,0,0]])

Or5 = np.array([[1,1,1,1,1],[1,0,0,1,1],[1,1,0,1,1],
                [1,1,1,0,1],[1,1,0,0,1]])

#Arreglo de prueba final
finalAND = np.array([[0,0,0,0],[1,0,1,0],[0,0,1,0],[1,1,1,1]])

finalOR = np.array([[0,0,0,0],[1,0,1,1],[0,0,1,1],[1,1,1,1]])

## Entrenamiento

No se si sea nesesario pero explicare los arreglos tomados en cada entrenamiento.

    1) Para el primer entrenamiento utilizamos las entradas con solo 0's y 1's como entrada ya que se puede considerar como la "base".
    2) Para el segundo entrenamiento utilice todos los valores posibles de forma acendente binariamente hablando.
    3) Para el tercero entrenamiento meti pares para que en el AND solo tuviera salidas en 0 y en el OR puras salidas en 1.
    4) Para el cuarto entrenamiento hice lo mismo que en el 2 pero ahora por la izquierda.
    5) Para el quinto tome entradas aleatorias sin ninguna consideracion extra.

In [87]:
#Primer entrenamiento
print("\nPrimera prueba")

print('AND')
print(perceptronAND.entrena(inicial,100))

print('OR')
print(perceptronOR.entrena(inicial,100))

#Segundo entrenamiento
print("\nSegunda prueba")

print('AND')
print(perceptronAND.entrena(And2,100))

print('OR')
print(perceptronOR.entrena(Or2,100))

#Tercer entrenamiento
print("\nTercera prueba")

print('AND')
print(perceptronAND.entrena(And3,100))

print('OR')
print(perceptronOR.entrena(Or3,100))

#Cuarto entrenamiento
print("\nCuarta prueba")

print('AND')
print(perceptronAND.entrena(And4,100))

print('OR')
print(perceptronOR.entrena(Or4,100))

#Quinto entrenamineto
print("\nQuinta prueba")

print('AND')
print(perceptronAND.entrena(And5,100))

print('OR')
print(perceptronOR.entrena(Or5,100))

#Prueba final
print("\nPrediccion final")

print('AND')
print(perceptronAND.prediccion(finalAND))

print('OR')
print(perceptronOR.prediccion(finalOR))


Primera prueba
AND
[0. 1.]
OR
[0. 1.]

Segunda prueba
AND
[0. 0. 0. 0. 0. 0. 0. 1.]
OR
[0. 1. 1. 1. 1. 1. 1. 1.]

Tercera prueba
AND
[0. 0. 0. 0. 0. 0.]
OR
[1. 1. 1. 1. 1. 1.]

Cuarta prueba
AND
[0. 0. 0. 0. 0. 0. 0. 1.]
OR
[0. 1. 1. 1. 1. 1. 1. 1.]

Quinta prueba
AND
[1. 0. 0. 0. 0.]
OR
[1. 1. 1. 1. 1.]

Prediccion final
AND
[0. 0. 0. 1.]
OR
[0. 1. 1. 1.]


## Notas y observaciones

Pasa algo raro al momento de ejecutar en entrenamiento, a veces si se entrena bien y otras veces no, note que esto pasaba cuando nuestro valor theta es negativo, pero no supe si era obligatorio dejar el rango de -0.5 a 0.5, asi que lo cambie de 0 a 0.5 para ver los valores correctos, de todos modos los valores que da el entrenamiento deberian ser estos (intentele hasta que les salga, les juro que si funciona):
```
Primera prueba
AND
[0. 1.]
OR
[0. 1.]

Segunda prueba
AND
[0. 0. 0. 0. 0. 0. 0. 1.]
OR
[0. 1. 1. 1. 1. 1. 1. 1.]

Tercera prueba
AND
[0. 0. 0. 0. 0. 0.]
OR
[1. 1. 1. 1. 1. 1.]

Cuarta prueba
AND
[0. 0. 0. 0. 0. 0. 0. 1.]
OR
[0. 1. 1. 1. 1. 1. 1. 1.]

Quinta prueba
AND
[1. 0. 0. 0. 0.]
OR
[1. 1. 1. 1. 1.]

Prediccion final
AND
[0. 0. 0. 1.]
OR
[0. 1. 1. 1.]
```